### PR TITLE
Final tweaks to new website

### PR DESCRIPTION
**Pull request by agaetep**

### CODE REVIEW

**Comment by ramereth** [comment]
@agaetep does this include any syncing of content that was merged in the old repo in the last few months?

**Comment by agaetep** [comment]
> @agaetep does this include any syncing of content that was merged in the old repo in the last few months?

Everything was up to date from the last sync!

**Comment by ramereth** [comment]
@agaetep I noticed that https://osuosl.org/services/powerdev/opence/ is different and I know we've had some updates on the staff page too.

**Comment by agaetep** [comment]
> @agaetep I noticed that https://osuosl.org/services/powerdev/opence/ is different and I know we've had some updates on the staff page too.

I'm sorry you're right. Last time I had updated this website there were also opence and staff page changes, so I assumed they were the same. Fixing that!

**Pull request merged**
