### PR TITLE
Migrating Pelican Website to Hugo

### PR DESCRIPTION
**Pull request by antoniagaete**

### CODE REVIEW

**Comment by ramereth** [comment]
@antoniagaete can you please move everything under the `website` folder into the root of this repository? Also when I try to run `hugo serve` and try to access the site, it's just a blank page. How are you deploying this?

**Comment by antoniagaete** [comment]
> @antoniagaete can you please move everything under the `website` folder into the root of this repository? Also when I try to run `hugo serve` and try to access the site, it's just a blank page. How are you deploying this?

Since it's in development, I'm running it with `hugo server -D`. The -D will populate all of the pages because they are currently marked as drafts. I can go through and remove the `draft: true` if you would like (since it will get removed eventually I assume), so you can run it with `hugo server`.

**Comment by ramereth** [comment]
@antoniagaete any reason why to set them as drafts? I don't see why we'd just go ahead and remove them.

**Comment by ramereth** [comment]
Also, I'm still getting a blank page. I do see the following:
```
WARN 2023/04/06 11:28:28 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```
Am I missing something else?

**Comment by antoniagaete** [comment]
> Also, I'm still getting a blank page. I do see the following:
> 
> ```
> WARN 2023/04/06 11:28:28 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> ```
> 
> Am I missing something else?

Hm, I don't see why you would be getting a blank page, everything should already be setup so you should be able to just run it with `hugo server -D`. Are you connecting to `localhost:1313`?

**Comment by antoniagaete** [comment]
@ramereth actually, I'm wondering if it might be an issue with the template being pulled as a submodule, which might not exist on your machine.

**Comment by ramereth** [comment]
@antoniagaete that seems to be what's going on. `.gitmodules` is empty in the repo.

**Comment by ramereth** [comment]
@antoniagaete getting the following error now:
```
Error: module "hugo-flex" not found; either add it as a Hugo Module or store it in "/home/lance/git/osl/website/themes".: module does not exist
```

**Comment by antoniagaete** [comment]
@ramereth I believe I found/removed where hugo-flex was being referenced, it was the first theme I had chosen but switched to one more similar to OSU's theme. Let me know if it still doesn't work

**Comment by ramereth** [comment]
I was finally able to view the site!

**Comment by antoniagaete** [comment]
I've started fixing up the theme to look more OSU-like, and have most - if not all - of the website functionality working. All that's left is to add the rest of the content and finalize the theme.

**Pull request merged**
