### PR TITLE
Refactor homepage

### PR DESCRIPTION
**Pull request by agaetep**

### CODE REVIEW

**Comment by ramereth** [comment]
@agaetep I think this looks great for non-mobile users, but I think we may want to improve the experience for mobile users:

1. The menu basically doesn't work
2. There's a lot of white space on the margins when using a mobile device.

My only other nit-pick is how the "ftp server rebuild" summary is shown on the index page. Not sure if you can do much, but the bullets look different than what they do on the blog page.

**Comment by agaetep** [comment]
I tried clearing the CSS file before rebuilding so the cache wouldn't affect the changes. I did this because I'm seeing different CSS between my development-hosted site, the staging site above, and the staging site opened in an incognito window. However, clearing the file made no difference.  @ramereth do you have any idea why this might be happening?

**Comment by ramereth** [comment]
@agaetep what specifically are you seeing that isn't correct?

**Comment by agaetep** [comment]
> @agaetep what specifically are you seeing that isn't correct?

For the blog summaries, I fixed the bullets but on this staging version they're not there (could be a url issue but I linked it to the website itself). Also, the image still shows up.

**Pull request merged**
