### PR TITLE
Update site content

### PR DESCRIPTION
**Pull request by antoniagaete**

### CODE REVIEW

**Review by ramereth — CHANGES_REQUESTED** [review]
A few issues
- The /services page isn't showing the landing page I'm expecting
- Not all URLs are the same between the current and new site (i.e. `/people` vs `/about/people`). Please make sure every URL is the same as the current site
- The contact page isn't displaying the addresses properly. It looks like you need to add two trailing spaces to each line to get Hugo to create a `<br>`
- There are some white spaces in `data/projects.yml` that should be removed. You might double check other files for extra white spaces.

**Comment by antoniagaete** [comment]
> * There are some white spaces in `data/projects.yml` that should be removed. You might double check other files for extra white spaces.

I don't see any white spaces, could you point them out to me?

**Comment by ramereth** [comment]
@antoniagaete depending on your editor, you can make it easier to find. But here's one example:

https://github.com/osuosl/website/blob/931eb5a9f943b86f8360212863f9a6ab5bdad218/data/projects.yml#L1

**Comment by antoniagaete** [comment]
@ramereth I had originally formatted it that way, but fixed it up to look more compact

**Review by ramereth — APPROVED** [review]

**Pull request merged**
